# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title : Modelling in Biology
author :
  name : Modelling in Biology
  email : willyrv@gmail.com
  github : github.com/willyrv

description: On Models and Modelling in Biology
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com" # the base hostname & protocol for your site
twitter_username: willy_r_v
github_username:  willyrv
# NOTE: If replacing this next line with your own URL, you likely want "https://" not "http://"
production_url : https://willyrv.github.io/OMMB
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
# NOTE: If replacing this next line with your own URL, you likely want "https://" not "http://"
BASE_PATH : https://willyrv.github.io/OMMB
